#pragma once
// auto-generated by vu hybrid sdk dumper
// static PE + IDA-derived engine model (+ optional live validation)

#include <cstdint>

namespace Vu::SDK::Engine
{
	constexpr std::uint32_t k_image_base = 0x400000;

	namespace Globals
	{
		constexpr std::uint32_t g_btbroadphaseaabbcallback = 0x3358b4; // va=0x7358b4 btBroadphaseAabbCallback [vftable_then_abs_store]
		constexpr std::uint32_t g_inprocmodule_details_platform = 0x358c10; // va=0x758c10 InProcModule@Details@Platform [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758F84 = 0x358f84; // va=0x758f84 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758F8C = 0x358f8c; // va=0x758f8c [abs_store_cluster]
		constexpr std::uint32_t g_vubarracudametrogfxcomposer = 0x358f94; // va=0x758f94 VuBarracudaMetroGfxComposer [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758F98 = 0x358f98; // va=0x758f98 [abs_store_cluster]
		constexpr std::uint32_t g_vumetroanalyticsmanager = 0x358f9c; // va=0x758f9c VuMetroAnalyticsManager [vftable_then_abs_store]
		constexpr std::uint32_t g_vumetrocloudsavemanager = 0x358fa0; // va=0x758fa0 VuMetroCloudSaveManager [vftable_then_abs_store]
		constexpr std::uint32_t g_vumetrocommunitymanager = 0x358fa4; // va=0x758fa4 VuMetroCommunityManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758FA8 = 0x358fa8; // va=0x758fa8 [abs_store_cluster]
		constexpr std::uint32_t g_vumetrolicensemanager = 0x358fac; // va=0x758fac VuMetroLicenseManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758FB0 = 0x358fb0; // va=0x758fb0 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FB4 = 0x358fb4; // va=0x758fb4 [abs_store_cluster]
		constexpr std::uint32_t g_vu_boat_manager = 0x358fb8; // va=0x758fb8 VuBoatManager [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FBC = 0x358fbc; // va=0x758fbc [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FC0 = 0x358fc0; // va=0x758fc0 [abs_store_cluster]
		constexpr std::uint32_t g_vufademanager = 0x358fc4; // va=0x758fc4 VuFadeManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758FC8 = 0x358fc8; // va=0x758fc8 [abs_store_cluster]
		constexpr std::uint32_t g_vuhiddenpackagemanagerimpl = 0x358fd0; // va=0x758fd0 VuHiddenPackageManagerImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758FD4 = 0x358fd4; // va=0x758fd4 [abs_store_cluster]
		constexpr std::uint32_t g_vuprogressmanagerimpl = 0x358fd8; // va=0x758fd8 VuProgressManagerImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_vu_project_manager = 0x358fdc; // va=0x758fdc VuProjectManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00758FE0 = 0x358fe0; // va=0x758fe0 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FE4 = 0x358fe4; // va=0x758fe4 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FE8 = 0x358fe8; // va=0x758fe8 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FEC = 0x358fec; // va=0x758fec [abs_store_cluster]
		constexpr std::uint32_t g_vu_game_mode_manager = 0x358ff0; // va=0x758ff0 VuGameModeManagerImpl [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FF4 = 0x358ff4; // va=0x758ff4 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00758FF8 = 0x358ff8; // va=0x758ff8 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759000 = 0x359000; // va=0x759000 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759004 = 0x359004; // va=0x759004 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759008 = 0x359008; // va=0x759008 [abs_store_cluster]
		constexpr std::uint32_t g_unk_0075900C = 0x35900c; // va=0x75900c [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759010 = 0x359010; // va=0x759010 [abs_store_cluster]
		constexpr std::uint32_t g_vu_dev_menu = 0x359014; // va=0x759014 VuDevMenu [vftable_then_abs_store]
		constexpr std::uint32_t g_vudev = 0x359018; // va=0x759018 VuDev [vftable_then_abs_store]
		constexpr std::uint32_t g_vudevconfig = 0x35901c; // va=0x75901c VuDevConfig [vftable_then_abs_store]
		constexpr std::uint32_t g_vudevstat = 0x359020; // va=0x759020 VuDevStat [vftable_then_abs_store]
		constexpr std::uint32_t g_vudrawmanagerimpl = 0x359024; // va=0x759024 VuDrawManagerImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_vueventmanager = 0x359028; // va=0x759028 VuEventManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_0075902C = 0x35902c; // va=0x75902c [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759030 = 0x359030; // va=0x759030 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759034 = 0x359034; // va=0x759034 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759038 = 0x359038; // va=0x759038 [abs_store_cluster]
		constexpr std::uint32_t g_unk_0075903C = 0x35903c; // va=0x75903c [abs_store_cluster]
		constexpr std::uint32_t g_vumetrogamepad = 0x359040; // va=0x759040 VuMetroGamePad [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00759048 = 0x359048; // va=0x759048 [abs_store_cluster]
		constexpr std::uint32_t g_unk_0075904C = 0x35904c; // va=0x75904c [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759058 = 0x359058; // va=0x759058 [abs_store_cluster]
		constexpr std::uint32_t g_unk_0075905C = 0x35905c; // va=0x75905c [abs_store_cluster]
		constexpr std::uint32_t g_vu_viewport_manager = 0x359060; // va=0x759060 VuViewportManager [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759064 = 0x359064; // va=0x759064 [abs_store_cluster]
		constexpr std::uint32_t g_vumetrokeyboard = 0x35906c; // va=0x75906c VuMetroKeyboard [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00759070 = 0x359070; // va=0x759070 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759074 = 0x359074; // va=0x759074 [abs_store_cluster]
		constexpr std::uint32_t g_unk_00759078 = 0x359078; // va=0x759078 [abs_store_cluster]
		constexpr std::uint32_t g_unk_0075907C = 0x35907c; // va=0x75907c [abs_store_cluster]
		constexpr std::uint32_t g_vu_entity_repository = 0x359080; // va=0x759080 VuEntityRepositoryImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_vumetroprofilemanager = 0x359084; // va=0x759084 VuMetroProfileManager [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00759088 = 0x359088; // va=0x759088 [abs_store_cluster]
		constexpr std::uint32_t g_vumetrofile = 0x35908c; // va=0x75908c VuMetroFile [vftable_then_abs_store]
		constexpr std::uint32_t g_vudevconsole = 0x359090; // va=0x759090 VuDevConsole [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_00759094 = 0x359094; // va=0x759094 [abs_store_cluster]
		constexpr std::uint32_t g_vumetrothread = 0x359098; // va=0x759098 VuMetroThread [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_0075909C = 0x35909c; // va=0x75909c [abs_store_cluster]
		constexpr std::uint32_t g_vudevprofile = 0x3590a0; // va=0x7590a0 VuDevProfile [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_007590B0 = 0x3590b0; // va=0x7590b0 [abs_store_cluster]
		constexpr std::uint32_t g_unk_007590B4 = 0x3590b4; // va=0x7590b4 [abs_store_cluster]
		constexpr std::uint32_t g_unk_007590B8 = 0x3590b8; // va=0x7590b8 [abs_store_cluster]
		constexpr std::uint32_t g_vugfxcomposer = 0x3590bc; // va=0x7590bc VuGfxComposer [vftable_then_abs_store]
		constexpr std::uint32_t g_vufoliagemanager = 0x3590dc; // va=0x7590dc VuFoliageManager [vftable_then_abs_store]
		constexpr std::uint32_t g_vumetronet = 0x3590e0; // va=0x7590e0 VuMetroNet [vftable_then_abs_store]
		constexpr std::uint32_t g_vuservicemanager = 0x3590e4; // va=0x7590e4 VuServiceManager [vftable_then_abs_store]
		constexpr std::uint32_t g_vutelemetryclientimpl = 0x3590e8; // va=0x7590e8 VuTelemetryClientImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_vutelemetryserverimpl = 0x3590ec; // va=0x7590ec VuTelemetryServerImpl [vftable_then_abs_store]
		constexpr std::uint32_t g_vudevtimer = 0x3590f0; // va=0x7590f0 VuDevTimer [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_007590F4 = 0x3590f4; // va=0x7590f4 [abs_store_cluster]
		constexpr std::uint32_t g_vumetrohttpclient = 0x3590f8; // va=0x7590f8 VuMetroHttpClient [vftable_then_abs_store]
		constexpr std::uint32_t g_unk_007590FC = 0x3590fc; // va=0x7590fc [abs_store_cluster]
		constexpr std::uint32_t g_vumetrod3d11vertexbuffer = 0x359748; // va=0x759748 VuMetroD3d11VertexBuffer [vftable_then_abs_store]
		constexpr std::uint32_t g_btidebugdraw = 0x359864; // va=0x759864 btIDebugDraw [vftable_then_abs_store]
		constexpr std::uint32_t g_vumetrod3d11rendertarget = 0x359878; // va=0x759878 VuMetroD3d11RenderTarget [vftable_then_abs_store]
		constexpr std::uint32_t g_vugamemode = 0x41994c; // va=0x81994c VuGameMode [vftable_then_abs_store]
	}

	namespace Fields
	{
		constexpr std::uint32_t VuAIUIDriverStartEntity_AISkins = 0x0; // VuColor -- loader=0x430830
		constexpr std::uint32_t VuAIUIDriverStartEntity_AssetDB = 0x0; // int32_t -- loader=0x430830
		constexpr std::uint32_t VuAIUIDriverStartEntity_Class = 0x0; // int32_t -- loader=0x430830
		constexpr std::uint32_t VuAIUIDriverStartEntity_VuDBAsset = 0x0; // int32_t -- loader=0x430830
		constexpr std::uint32_t VuAchievementManager_VuDBAsset = 0x0; // int32_t -- loader=0x4A9D00
		constexpr std::uint32_t VuAiDriver_Name = 0x98; // float -- loader=0x40B8A0
		constexpr std::uint32_t VuAnimation_Additive = 0x0; // int32_t -- loader=0x515ED0
		constexpr std::uint32_t VuAnimation_File = 0x0; // int32_t -- loader=0x515ED0
		constexpr std::uint32_t VuAssetFactoryImpl_Assets = 0x0; // int32_t -- loader=0x4EED30
		constexpr std::uint32_t VuAssetFactoryImpl_Langs = 0x0; // int32_t -- loader=0x4EE3B0
		constexpr std::uint32_t VuAssetFactoryImpl_LicenseMask = 0x0; // bool -- loader=0x4EF610
		constexpr std::uint32_t VuAssetFactoryImpl_Packages = 0xf0; // int32_t -- loader=0x4ECF90
		constexpr std::uint32_t VuAssetFactoryImpl_Skus = 0xf0; // int32_t -- loader=0x4ECF90
		constexpr std::uint32_t VuBaseConfigEntity_VuDBAsset = 0x0; // int32_t -- loader=0x449640
		constexpr std::uint32_t VuBoatEntity_AI = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Ambient_Color = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Audio = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_BoostMisfire = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Class = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Collision_Mesh_Asset = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Destruction = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Diffuse_Color = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Drafting = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Driver = 0x0; // int32_t -- loader=0x41CFF0
		constexpr std::uint32_t VuBoatEntity_Jump = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_JumpMisfire = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_LOD_1_Model_Asset = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_LOD_2_Model_Asset = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Model_Asset = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Player = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Pos = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_SlalomBounds = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_StringID = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Surface_Type = 0x0; // int32_t -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_LOD_1_Distance = 0x10c; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_LOD_2_Distance = 0x110; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Mass = 0x134; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Min_Jump_Speed = 0x138; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Vertical_Jump_Speed = 0x13c; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Destruction_Speed = 0x140; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_InertiaFactor = 0x144; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Radius = 0x1a0; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_SlalomBounds = 0x1a0; // float -- loader=0x4205A0
		constexpr std::uint32_t VuBoatEntity_Engine = 0x22c; // c_VuBoatEntity_Engine* -> VuBoatEntity_Engine -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Pfx = 0x234; // c_VuBoatEntity_Pfx* -> VuBoatEntity_Pfx -- loader=0x41A1A0
		constexpr std::uint32_t VuBoatEntity_Engine_Max_Steering_Angle = 0x8; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Max_Forward_Speed = 0xc; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Max_Reverse_Speed = 0x10; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Max_Thrust = 0x14; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Air_Boost_Long_Thrust = 0x18; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Air_Boost_Lat_Thrust = 0x1c; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Reverse_Ratio = 0x20; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Out_of_Water_Ratio = 0x24; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Boost_Speed_Modifier = 0x28; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Boost_Thrust_Modifier = 0x2c; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Engine_Power_Curve = 0xd4; // float -- loader=0x4140C0
		constexpr std::uint32_t VuBoatEntity_Pfx_Bone = 0x84; // float -- loader=0x41A1A0
		constexpr std::uint32_t VuBreakablePropEntity_Events = 0x0; // int32_t -- loader=0x546FB0
		constexpr std::uint32_t VuBreakablePropEntity_Reverbs = 0x0; // int32_t -- loader=0x546FB0
		constexpr std::uint32_t VuCamera_Velocity = 0x20; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuCamera_ProjMatrix = 0x30; // VuMatrix4 -- ida/structural
		constexpr std::uint32_t VuCamera_ViewMatrix = 0xf0; // VuMatrix4 -- ida/structural
		constexpr std::uint32_t VuCamera_Forward = 0x140; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuCamera_Up = 0x150; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuCamera_EyePosition = 0x160; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuCloudManager_Alert = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_Cloud = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_Data = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_IdentitySaved = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_LastCheckTime = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_News = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuCloudManager_Tuning = 0x0; // int32_t -- loader=0x5C62C0
		constexpr std::uint32_t VuDBAsset_Achievement = 0x0; // int32_t -- loader=0x492540
		constexpr std::uint32_t VuDBAsset_Achievements = 0x0; // int32_t -- loader=0x4DCD30
		constexpr std::uint32_t VuDBAsset_ActionGameData = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_Animation = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_Announcer = 0x0; // int32_t -- loader=0x44E140
		constexpr std::uint32_t VuDBAsset_ApplyPfx = 0x0; // int32_t -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_AssetDB = 0x0; // int32_t -- loader=0x4D3AA0
		constexpr std::uint32_t VuDBAsset_Audio = 0x0; // int32_t -- loader=0x44E140
		constexpr std::uint32_t VuDBAsset_AudioEvent = 0x0; // int32_t -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_AutoThrottleGamePad = 0x0; // int32_t -- loader=0x4B4E20
		constexpr std::uint32_t VuDBAsset_AutoThrottleKeyboard = 0x0; // int32_t -- loader=0x4B4EA0
		constexpr std::uint32_t VuDBAsset_Boat = 0x0; // int32_t -- loader=0x436060
		constexpr std::uint32_t VuDBAsset_BoatConfig = 0x0; // int32_t -- loader=0x452E00
		constexpr std::uint32_t VuDBAsset_Camera = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_Champ_Completed = 0x0; // int32_t -- loader=0x452890
		constexpr std::uint32_t VuDBAsset_Championship = 0x0; // int32_t -- loader=0x452E00
		constexpr std::uint32_t VuDBAsset_Choices = 0x0; // int32_t -- loader=0x47BC90
		constexpr std::uint32_t VuDBAsset_Class = 0x0; // int32_t -- loader=0x452E00
		constexpr std::uint32_t VuDBAsset_Course = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_Credits = 0x0; // bool -- loader=0x4B7250
		constexpr std::uint32_t VuDBAsset_Damage = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_Default = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_DefaultBoatProperties = 0x0; // int32_t -- loader=0x436060
		constexpr std::uint32_t VuDBAsset_DefaultSettings = 0x0; // int32_t -- loader=0x4B4E20
		constexpr std::uint32_t VuDBAsset_DoneInfoStringID = 0x0; // int32_t -- loader=0x452890
		constexpr std::uint32_t VuDBAsset_DriverName = 0x0; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_Engine = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_Events = 0x0; // int32_t -- loader=0x455210
		constexpr std::uint32_t VuDBAsset_GameConfig = 0x0; // int32_t -- loader=0x44E140
		constexpr std::uint32_t VuDBAsset_GameData = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_GameType = 0x0; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_Hull = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_InfoStringID = 0x0; // int32_t -- loader=0x452890
		constexpr std::uint32_t VuDBAsset_IsChampionship = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_LocalUnlocked = 0x0; // int32_t -- loader=0x4DCD30
		constexpr std::uint32_t VuDBAsset_Metro = 0x0; // int32_t -- loader=0x4B4E20
		constexpr std::uint32_t VuDBAsset_Mode = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_Name = 0x0; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_Pfx = 0x0; // int32_t -- loader=0x420A70
		constexpr std::uint32_t VuDBAsset_PlayerBoats = 0x0; // int32_t -- loader=0x452E00
		constexpr std::uint32_t VuDBAsset_PosterModel = 0x0; // int32_t -- loader=0x452890
		constexpr std::uint32_t VuDBAsset_ProjectAsset = 0x0; // int32_t -- loader=0x4C0A50
		constexpr std::uint32_t VuDBAsset_Properties = 0x0; // int32_t -- loader=0x452E00
		constexpr std::uint32_t VuDBAsset_References = 0x0; // int32_t -- loader=0x44A4C0
		constexpr std::uint32_t VuDBAsset_Round = 0x0; // bool -- loader=0x455210
		constexpr std::uint32_t VuDBAsset_Skin = 0x0; // int32_t -- loader=0x436060
		constexpr std::uint32_t VuDBAsset_Slalom = 0x0; // int32_t -- loader=0x48DE10
		constexpr std::uint32_t VuDBAsset_StaticPfx = 0x0; // int32_t -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_StringID = 0x0; // int32_t -- loader=0x44A4C0
		constexpr std::uint32_t VuDBAsset_Subtitles = 0x0; // int32_t -- loader=0x4B4C60
		constexpr std::uint32_t VuDBAsset_Tasks = 0x0; // int32_t -- loader=0x4AA350
		constexpr std::uint32_t VuDBAsset_TiltSteering = 0x0; // int32_t -- loader=0x4B4F00
		constexpr std::uint32_t VuDBAsset_TimeTrial = 0x0; // int32_t -- loader=0x490750
		constexpr std::uint32_t VuDBAsset_Track = 0x0; // int32_t -- loader=0x47BC90
		constexpr std::uint32_t VuDBAsset_Type = 0x0; // int32_t -- loader=0x4B6CC0
		constexpr std::uint32_t VuDBAsset_Units = 0x0; // int32_t -- loader=0x4B4FC0
		constexpr std::uint32_t VuDBAsset_Unlockables = 0x0; // int32_t -- loader=0x4B6CC0
		constexpr std::uint32_t VuDBAsset_Value = 0x0; // int32_t -- loader=0x47BC90
		constexpr std::uint32_t VuDBAsset_Vibration = 0x0; // int32_t -- loader=0x4B4E20
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x0; // int32_t -- loader=0x41D500
		constexpr std::uint32_t VuDBAsset_XBLID = 0x0; // bool -- loader=0x492540
		constexpr std::uint32_t VuDBAsset_DisallowedModes = 0x8; // int32_t -- loader=0x4D3D40
		constexpr std::uint32_t VuDBAsset_Size = 0x20; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_DefaultSettings = 0x24; // float -- loader=0x4B4C60
		constexpr std::uint32_t VuDBAsset_EffectVolume = 0x24; // float -- loader=0x4B4C60
		constexpr std::uint32_t VuDBAsset_Metro = 0x24; // float -- loader=0x4B4C60
		constexpr std::uint32_t VuDBAsset_MusicVolume = 0x24; // float -- loader=0x4B4C60
		constexpr std::uint32_t VuDBAsset_Times = 0x24; // float -- loader=0x48DE10
		constexpr std::uint32_t VuDBAsset_Weight = 0x24; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_Softness = 0x28; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_Color = 0x30; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_OutlineWeight = 0x30; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_SteeringSensitivity = 0x30; // float -- loader=0x4B4F00
		constexpr std::uint32_t VuDBAsset_OutlineSoftness = 0x34; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_Slant = 0x3c; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_DefaultSettings = 0x40; // float -- loader=0x4B4FC0
		constexpr std::uint32_t VuDBAsset_Metro = 0x40; // float -- loader=0x4B4FC0
		constexpr std::uint32_t VuDBAsset_OutlineColor = 0x40; // bool -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_TabSize = 0x40; // bool -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x40; // float -- loader=0x4B4FC0
		constexpr std::uint32_t VuDBAsset_Stretch = 0x44; // float -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_FontAsset = 0x60; // int32_t -- loader=0x626CF0
		constexpr std::uint32_t VuDBAsset_AccelerometerSteeringExtents = 0x90; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x90; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_AccelerometerSteeringExtents = 0x94; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x94; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_AccelerometerCameraDamping = 0x98; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x98; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_GamePadCameraTilt = 0x9c; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0x9c; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_HUD = 0xa0; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xa0; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_WrongWaySpeedThreshold = 0xa0; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_HUD = 0xa4; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xa4; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_WrongWayAngleThreshold = 0xa4; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_HUD = 0xa8; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xa8; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_WrongWayInertiaTime = 0xa8; // float -- loader=0x40ED50
		constexpr std::uint32_t VuDBAsset_References = 0xb4; // int32_t -- loader=0x4795D6
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xb4; // int32_t -- loader=0x4795CA
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xc4; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_AI = 0xcc; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_AIBoats = 0xcc; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_DriverName = 0xcc; // int32_t -- loader=0x4C2300
		constexpr std::uint32_t VuDBAsset_Properties = 0xcc; // int32_t -- loader=0x4C18D0
		constexpr std::uint32_t VuDBAsset_Skin = 0xcc; // int32_t -- loader=0x4C18D0
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xcc; // int32_t -- loader=0x4D2010
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xd0; // int32_t -- loader=0x4C18D0
		constexpr std::uint32_t VuDBAsset_Boat = 0xd4; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_GameConfig = 0xd4; // int32_t -- loader=0x459D70
		constexpr std::uint32_t VuDBAsset_Radius = 0xe0; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_FadeTime = 0xe4; // float -- loader=0x4C6AB0
		constexpr std::uint32_t VuDBAsset_RecoverTime = 0xe4; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_WaitTime = 0xe4; // float -- loader=0x4C6AB0
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xe8; // int32_t -- loader=0x4D2010
		constexpr std::uint32_t VuDBAsset_Screens = 0xec; // int32_t -- loader=0x4C6AB0
		constexpr std::uint32_t VuDBAsset_TitleSequence = 0xec; // int32_t -- loader=0x4C6AB0
		constexpr std::uint32_t VuDBAsset_Boat = 0xf0; // float -- loader=0x422310
		constexpr std::uint32_t VuDBAsset_GhostFadeDist = 0xf0; // float -- loader=0x422310
		constexpr std::uint32_t VuDBAsset_TransitionDuration = 0xf0; // float -- loader=0x4BEEA0
		constexpr std::uint32_t VuDBAsset_UI = 0xf0; // float -- loader=0x4BEEA0
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xf0; // float -- loader=0x422310
		constexpr std::uint32_t VuDBAsset_Type = 0xf4; // int32_t -- loader=0x4B7250
		constexpr std::uint32_t VuDBAsset_Unlockables = 0xf4; // int32_t -- loader=0x4B7250
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xf4; // int32_t -- loader=0x4B7250
		constexpr std::uint32_t VuDBAsset_Name = 0xf8; // int32_t -- loader=0x4B7430
		constexpr std::uint32_t VuDBAsset_AISkins = 0xfc; // float -- loader=0x4C31D0
		constexpr std::uint32_t VuDBAsset_Class = 0xfc; // int32_t -- loader=0x455360
		constexpr std::uint32_t VuDBAsset_Feats = 0xfc; // int32_t -- loader=0x4B7430
		constexpr std::uint32_t VuDBAsset_VuDBAsset = 0xfc; // int32_t -- loader=0x4B7430
		constexpr std::uint32_t VuDBAsset_ScaleSpringCoeff = 0x100; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_ScaleDampingCoeff = 0x104; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_ScaleInitial = 0x108; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBAsset_ScaleInitialVelocity = 0x10c; // float -- loader=0x43C1F0
		constexpr std::uint32_t VuDBEntryProperty_VuDBAsset = 0x0; // int32_t -- loader=0x506B30
		constexpr std::uint32_t VuDriverEntity_Name = 0xfc; // float -- loader=0x40EAC0
		constexpr std::uint32_t VuEntity_ChildEntities = 0x0; // int32_t -- loader=0x5009D0
		constexpr std::uint32_t VuEntity_Properties = 0x0; // int32_t -- loader=0x5009D0
		constexpr std::uint32_t VuEntity_Components = 0x30; // int32_t -- loader=0x5009D0
		constexpr std::uint32_t VuGfxScene_File = 0x0; // int32_t -- loader=0x519CC0
		constexpr std::uint32_t VuGfxScene_FlipX = 0x0; // int32_t -- loader=0x519CC0
		constexpr std::uint32_t VuGfxScene_VuAnimatedModel = 0x0; // int32_t -- loader=0x4C8650
		constexpr std::uint32_t VuGfxScene_VuAnimation = 0x0; // int32_t -- loader=0x4C8650
		constexpr std::uint32_t VuGfxScene_VuGfxScene = 0x0; // int32_t -- loader=0x4C8650
		constexpr std::uint32_t VuGfxScene_VuAnimation = 0xf0; // int32_t -- loader=0x4C8650
		constexpr std::uint32_t VuGhostBoatEntity_Boat = 0x0; // int32_t -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_HollywoodMaxLinVel = 0x0; // int32_t -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_HollywoodMinAngVel = 0x0; // int32_t -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_HollywoodMinLinVel = 0x0; // int32_t -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_VuDBAsset = 0x0; // int32_t -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_Boat = 0x4; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_HollywoodMaxAngVel = 0x4; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_VuDBAsset = 0x4; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_BeachedSpeedThreshold = 0x38c; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_Boat = 0x38c; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_VuDBAsset = 0x38c; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_BeachedTimeInAirThreshold = 0x390; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_Boat = 0x390; // float -- loader=0x41B850
		constexpr std::uint32_t VuGhostBoatEntity_VuDBAsset = 0x390; // float -- loader=0x41B850
		constexpr std::uint32_t VuHUDOnScreenAxisEntity_Axes = 0x0; // int32_t -- loader=0x4291A0
		constexpr std::uint32_t VuHUDOnScreenAxisEntity_Buttons = 0x0; // int32_t -- loader=0x4291A0
		constexpr std::uint32_t VuHUDOnScreenAxisEntity_Name = 0x0; // int32_t -- loader=0x4291A0
		constexpr std::uint32_t VuHUDOnScreenAxisEntity_VuDBAsset = 0x0; // int32_t -- loader=0x4291A0
		constexpr std::uint32_t VuHUDOnScreenAxisEntity_Name = 0xf0; // int32_t -- loader=0x429260
		constexpr std::uint32_t VuHUDOnScreenButtonEntity_Buttons = 0x0; // int32_t -- loader=0x429110
		constexpr std::uint32_t VuHUDOnScreenButtonEntity_VuDBAsset = 0x0; // int32_t -- loader=0x429110
		constexpr std::uint32_t VuHiddenPackageManagerImpl_PackagesFound = 0x0; // int32_t -- loader=0x4AFFA0
		constexpr std::uint32_t VuHiddenPackageManagerImpl_PackagesInLevel = 0x0; // bool -- loader=0x4B0000
		constexpr std::uint32_t VuHiddenPackageManagerImpl_VuDBAsset = 0x0; // bool -- loader=0x4B0000
		constexpr std::uint32_t VuHiddenPackageManagerImpl_PackagesFound = 0x8; // int32_t -- loader=0x4B0090
		constexpr std::uint32_t VuMetroAchievementManager_VuDBAsset = 0x0; // int32_t -- loader=0x4913A0
		constexpr std::uint32_t VuMetroAchievementManager_XBLID = 0x0; // bool -- loader=0x4913A0
		constexpr std::uint32_t VuMetroAnalyticsManager_Difficulty = 0x0; // int32_t -- loader=0x492380
		constexpr std::uint32_t VuMotionComponentIF_DisabledInGames = 0x0; // int32_t -- loader=0x43B9D0
		constexpr std::uint32_t VuMotionComponentIF_VuDBAsset = 0x0; // int32_t -- loader=0x43B9D0
		constexpr std::uint32_t VuPfxBoatSpringConstraintInstance_ChildNodes = 0x0; // int32_t -- loader=0x563D40
		constexpr std::uint32_t VuPfxBoatSpringConstraintInstance_Properties = 0x0; // int32_t -- loader=0x563D40
		constexpr std::uint32_t VuPowerUpBoostEntity_ApplyPfx = 0x0; // int32_t -- loader=0x43D960
		constexpr std::uint32_t VuPowerUpBoostEntity_AudioEvent = 0x0; // int32_t -- loader=0x43D960
		constexpr std::uint32_t VuPowerUpBoostEntity_MPBoost = 0x0; // int32_t -- loader=0x43D960
		constexpr std::uint32_t VuPowerUpBoostEntity_StaticPfx = 0x0; // int32_t -- loader=0x43D960
		constexpr std::uint32_t VuPowerUpBoostEntity_VuDBAsset = 0x0; // int32_t -- loader=0x43D960
		constexpr std::uint32_t VuPowerUpBoostEntity_BoostEnergy = 0x13c; // float -- loader=0x43DA90
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeChampionshipBronzes = 0x0; // bool -- loader=0x4B3C80
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeChampionshipCount = 0x0; // bool -- loader=0x4B3A30
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeChampionshipGolds = 0x0; // bool -- loader=0x4B3C80
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeChampionshipSilvers = 0x0; // bool -- loader=0x4B3C80
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeRaceBronzes = 0x0; // bool -- loader=0x4B34D0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeRaceCount = 0x0; // bool -- loader=0x4B32D0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeRaceGolds = 0x0; // bool -- loader=0x4B34D0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeRaceSilvers = 0x0; // bool -- loader=0x4B34D0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeSlalomBronzes = 0x0; // bool -- loader=0x4B3660
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeSlalomCount = 0x0; // bool -- loader=0x4B3430
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeSlalomGolds = 0x0; // bool -- loader=0x4B3660
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeSlalomSilvers = 0x0; // bool -- loader=0x4B3660
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeTimeTrialBronzes = 0x0; // bool -- loader=0x4B37F0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeTimeTrialCount = 0x0; // bool -- loader=0x4B3380
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeTimeTrialGolds = 0x0; // bool -- loader=0x4B37F0
		constexpr std::uint32_t VuProgressManagerImpl_AllTimeTimeTrialSilvers = 0x0; // bool -- loader=0x4B37F0
		constexpr std::uint32_t VuProgressManagerImpl_BestLap = 0x0; // bool -- loader=0x4B1930
		constexpr std::uint32_t VuProgressManagerImpl_Championship = 0x0; // int32_t -- loader=0x4B3980
		constexpr std::uint32_t VuProgressManagerImpl_ChampionshipState = 0x0; // int32_t -- loader=0x4B3D90
		constexpr std::uint32_t VuProgressManagerImpl_Ghost = 0x0; // bool -- loader=0x4B3F90
		constexpr std::uint32_t VuProgressManagerImpl_Place = 0x0; // bool -- loader=0x4B1930
		constexpr std::uint32_t VuProgressManagerImpl_Progress = 0x0; // int32_t -- loader=0x4B22A0
		constexpr std::uint32_t VuProgressManagerImpl_TotalTime = 0x0; // bool -- loader=0x4B1930
		constexpr std::uint32_t VuProgressManagerImpl_BestLap = 0x24; // float -- loader=0x4B22A0
		constexpr std::uint32_t VuProgressManagerImpl_TotalTime = 0x24; // float -- loader=0x4B22A0
		constexpr std::uint32_t VuProgressManagerImpl_Progress = 0xd0; // int32_t -- loader=0x4B4090
		constexpr std::uint32_t VuProgressManagerImpl_BoatsUsed = 0xd8; // int32_t -- loader=0x4B4090
		constexpr std::uint32_t VuProject_File = 0x0; // int32_t -- loader=0x554F10
		constexpr std::uint32_t VuProject_RootEntity = 0x0; // int32_t -- loader=0x555450
		constexpr std::uint32_t VuProject_VuProject = 0x0; // int32_t -- loader=0x555450
		constexpr std::uint32_t VuProject_data = 0x0; // int32_t -- loader=0x556390
		constexpr std::uint32_t VuProject_type = 0x0; // int32_t -- loader=0x556390
		constexpr std::uint32_t VuProject_RootEntity = 0x4c; // int32_t -- loader=0x556E70
		constexpr std::uint32_t VuProject_VuProject = 0x4c; // int32_t -- loader=0x556E70
		constexpr std::uint32_t VuProject_data = 0x4c; // int32_t -- loader=0x556E70
		constexpr std::uint32_t VuRaceResultsTableEntity_ActionGameData = 0x0; // int32_t -- loader=0x469A20
		constexpr std::uint32_t VuRaceResultsTableEntity_GameData = 0x0; // int32_t -- loader=0x469A20
		constexpr std::uint32_t VuRaceResultsTableEntity_IsChampionship = 0x0; // int32_t -- loader=0x469A20
		constexpr std::uint32_t VuScriptComponent_Connections = 0x0; // int32_t -- loader=0x503D70
		constexpr std::uint32_t VuScriptComponent_Plugs = 0x0; // int32_t -- loader=0x503D70
		constexpr std::uint32_t VuScriptComponent_Position = 0x0; // int32_t -- loader=0x503D70
		constexpr std::uint32_t VuScriptComponent_RefConnections = 0x0; // int32_t -- loader=0x503D70
		constexpr std::uint32_t VuScriptComponent_Refs = 0x0; // int32_t -- loader=0x503D70
		constexpr std::uint32_t VuScriptComponent_Width = 0x48; // bool -- loader=0x503D70
		constexpr std::uint32_t VuShaderAsset_File = 0x0; // int32_t -- loader=0x53FF70
		constexpr std::uint32_t VuShaderAsset_Macros = 0x0; // int32_t -- loader=0x53FF70
		constexpr std::uint32_t VuStringDBImpl_File = 0x0; // int32_t -- loader=0x53C1F0
		constexpr std::uint32_t VuStringDBImpl_Langs = 0x0; // int32_t -- loader=0x53C1F0
		constexpr std::uint32_t VuTextureAsset_AddressV = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_Compression = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_ETC_Dithering = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_ETC_Quality = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_File = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_MagFilter = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_Type = 0x0; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_MinFilter = 0x58; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuTextureAsset_MipFilter = 0x58; // int32_t -- loader=0x5397E0
		constexpr std::uint32_t VuViewportManager_ViewportCount = 0x4; // int32_t -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera = 0x28; // vu_custom_t -- ida/structural getCamera(0); size=0x240; stride=0x274
		constexpr std::uint32_t VuViewportManager_Camera0_ProjMatrix = 0x58; // VuMatrix4 -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera0_ViewMatrix = 0x118; // VuMatrix4 -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera0_Forward = 0x168; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera0_Up = 0x178; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera0_EyePosition = 0x188; // VuVector3 -- ida/structural
		constexpr std::uint32_t VuViewportManager_Camera1 = 0x29c; // vu_custom_t -- ida/structural getCamera(i); size=0x240
		constexpr std::uint32_t VuViewportManager_Camera2 = 0x510; // vu_custom_t -- ida/structural getCamera(i); size=0x240
		constexpr std::uint32_t VuViewportManager_Camera3 = 0x784; // vu_custom_t -- ida/structural getCamera(i); size=0x240
	}

	namespace Chains
	{
		// boats
		// Dynamically resolved boat manager chain. Boost/name/transform steps only appear when those members were recovered from loaders or live property lists.
		//   [0] boat_manager <- module | read<VuBoatManager*>(module + rva) (0x358fb8 rva)
		//   [1] boat_entity <- boats_data[i] | VuBoatEntity*

		// camera
		// VuViewportManager::getCamera(i): embedded VuCamera at manager+0x28 + i*0x274 (size 0x240). Recovered from HydroThunder ctor sub_530B00, camera ctor sub_50BA20, and memcpy/FMOD sites.
		//   [0] viewport_manager <- module | read<VuViewportManager*>(module + rva) (0x359060 rva)
		//   [1] viewport_count <- viewport_manager | read<int>(viewport_manager + 0x4) (0x4)
		//   [2] camera <- viewport_manager | VuCamera* = viewport_manager + 0x28 + i*0x274  // getCamera(i) (0x28)
		//   [3] eye <- camera | VuVector3 at camera + 0x160  // FMOD listener / eye (0x160)
		//   [4] view_matrix <- camera | VuMatrix4 at camera + 0xF0 (0xf0)
		//   [5] proj_matrix <- camera | VuMatrix4 at camera + 0x30 (0x30)
		//   [6] forward <- camera | VuVector3 at camera + 0x140 (0x140)
		//   [7] up <- camera | VuVector3 at camera + 0x150 (0x150)

	}
}
