#pragma once
// auto-generated by vu static sdk dumper
// property loaders that could not be bound to an RTTI class

#include <cstdint>
#include "types.hpp"

namespace Vu::SDK::Orphans
{
	struct loader_00404810_t
	{
		int32_t m_position; // 0x0 "Position" loader=0x404810
		std::uint8_t pad_0x4[0x4];
		int32_t m_position_1; // 0x8 "Position" loader=0x404810
		std::uint8_t pad_0xc[0xf0];
		int32_t m_event; // 0xfc "Event" loader=0x404810
	};

	struct loader_004119F0_t
	{
		int32_t m_dest; // 0x0 "Dest" loader=0x4119f0
	};

	struct loader_00412270_t
	{
		int32_t m_asset; // 0x0 "Asset" loader=0x412270
		// alias +0x0 "CenterOfMass" (int32_t)
		// alias +0x0 "MaxRelAngVel" (int32_t)
		// alias +0x0 "MaxRelLinVel" (int32_t)
		// alias +0x0 "MinRelAngVel" (int32_t)
		// alias +0x0 "MinRelLinVel" (int32_t)
		// alias +0x0 "Pfx" (int32_t)
		std::uint8_t pad_0x4[0x20];
		float m_buoyancy; // 0x24 "Buoyancy" loader=0x412270
		// alias +0x24 "Mass" (float)
		// alias +0x24 "SkinFricion" (float)
	};

	struct loader_00426D70_t
	{
		int32_t m_minimap; // 0x0 "MiniMap" loader=0x426d70
		// alias +0x0 "Origin" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
		// alias +0x0 "WaterColor" (int32_t)
		std::uint8_t pad_0x4[0xb4];
		int32_t m_texture; // 0xb8 "Texture" loader=0x426d70
		std::uint8_t pad_0xbc[0x8];
		float m_scale; // 0xc4 "Scale" loader=0x426d70
		float m_viewdist; // 0xc8 "ViewDist" loader=0x426d70
		float m_softness; // 0xcc "Softness" loader=0x426d70
		std::uint8_t pad_0xd0[0xfffff82c];
		int32_t m_texture_1; // 0xfffff8fc "Texture" loader=0x426d70
	};

	struct loader_0042CB00_t
	{
		int32_t m_actiongamedata; // 0x0 "ActionGameData" loader=0x42cb00
		// alias +0x0 "EventType" (int32_t)
		// alias +0x0 "GameData" (int32_t)
	};

	struct loader_0042DAA0_t
	{
		int32_t m_android; // 0x0 "Android" loader=0x42daa0
		// alias +0x0 "IsTegra" (int32_t)
		// alias +0x0 "Platform" (int32_t)
	};

	struct loader_0042E570_t
	{
		int32_t m_achievements; // 0x0 "Achievements" loader=0x42e570
		// alias +0x0 "LocalUnlocked" (int32_t)
	};

	struct loader_00435CC0_t
	{
		int32_t m_iscrazy; // 0x0 "IsCrazy" loader=0x435cc0
	};

	struct loader_00436230_t
	{
		int32_t m_boat; // 0x0 "Boat" loader=0x436230
		// alias +0x0 "Properties" (int32_t)
	};

	struct loader_0043AEA0_t
	{
		std::uint8_t pad_0x0[0x7c];
		int32_t m_locked; // 0x7c "Locked" loader=0x43aea0
		// alias +0x7c "Poster" (int32_t)
	};

	struct loader_00448F50_t
	{
		bool m_comboboxid; // 0x0 "ComboBoxID" lane=0x0 byte=0 mask=0xff shift=0 loader=0x448f50
	};

	struct loader_00449050_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x449050
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
	};

	struct loader_004491C0_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x4491c0
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
	};

	struct loader_00449350_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x449350
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
	};

	struct loader_004494D0_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x4494d0
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
	};

	struct loader_00449830_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x449830
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
	};

	struct loader_00449B20_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x449b20
		// alias +0x0 "Value" (int32_t)
		std::uint8_t pad_0x4[0x4];
		VuColor m_name; // 0x8 "Name" loader=0x449b20
	};

	struct loader_0044B0D0_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x44b0d0
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Options" (int32_t)
		// alias +0x0 "Value" (int32_t)
		std::uint8_t pad_0x4[0x54];
		int32_t m_value; // 0x58 "Value" loader=0x44b0d0
	};

	struct loader_0044B780_t
	{
		int32_t m_value; // 0x0 "Value" loader=0x44b780
		std::uint8_t pad_0x4[0xdc];
		bool m_comboboxid; // 0xe0 "ComboBoxID" lane=0xe0 byte=0 mask=0xff shift=0 loader=0x44b780
		std::uint8_t pad_0xe1[0x3];
		int32_t m_choices; // 0xe4 "Choices" loader=0x44b780
		std::uint8_t pad_0xe8[0x8];
		int32_t m_name; // 0xf0 "Name" loader=0x44b780
	};

	struct loader_0044B9C0_t
	{
		int32_t m_infostringid; // 0x0 "InfoStringID" loader=0x44b9c0
	};

	struct loader_0044BD50_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x44bd50
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Value" (int32_t)
		std::uint8_t pad_0x4[0xf8];
		int32_t m_gameconfig; // 0xfc "GameConfig" loader=0x44bd50
	};

	struct loader_0044BE90_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x44be90
	};

	struct loader_0044BEE0_t
	{
		bool m_comboboxid; // 0x0 "ComboBoxID" lane=0x0 byte=0 mask=0xff shift=0 loader=0x44bee0
	};

	struct loader_0044E010_t
	{
		int32_t m_boat; // 0x0 "Boat" loader=0x44e010
		// alias +0x0 "Skin" (int32_t)
	};

	struct loader_0044E090_t
	{
		bool m_boat; // 0x0 "Boat" lane=0x0 byte=0 mask=0xff shift=0 loader=0x44e090
		// alias +0x0 "GameConfig" lane=0x0 byte=0 mask=0xff shift=0 loader=0x44e090
		// alias +0x0 "Skin" (int32_t)
	};

	struct loader_0044E510_t
	{
		int32_t m_boat; // 0x0 "Boat" loader=0x44e510
		// alias +0x0 "VuDBAsset" (int32_t)
		std::uint8_t pad_0x4[0xec];
		bool m_stats; // 0xf0 "Stats" lane=0xf0 byte=0 mask=0xff shift=0 loader=0x44e510
	};

	struct loader_0044E6E0_t
	{
		int32_t m_boat; // 0x0 "Boat" loader=0x44e6e0
		// alias +0x0 "Skin" (int32_t)
		// alias +0x0 "Team" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
	};

	struct loader_00451720_t
	{
		int32_t m_course; // 0x0 "Course" loader=0x451720
		// alias +0x0 "Track" (int32_t)
		// alias +0x0 "Type" (int32_t)
	};

	struct loader_00453590_t
	{
		int32_t m_aiskins; // 0x0 "AISkins" loader=0x453590
		// alias +0x0 "VuDBAsset" (int32_t)
	};

	struct loader_00453F40_t
	{
		int32_t m_properties; // 0x0 "Properties" loader=0x453f40
		// alias +0x0 "Skin" (int32_t)
	};

	struct loader_004540D0_t
	{
		int32_t m_drivername; // 0x0 "DriverName" loader=0x4540d0
		// alias +0x0 "GameResults" (int32_t)
		// alias +0x0 "IsHuman" (int32_t)
		// alias +0x0 "Table" (int32_t)
		std::uint8_t pad_0x4[0x4];
		bool m_round; // 0x8 "Round" lane=0x8 byte=0 mask=0xff shift=0 loader=0x4540d0
	};

	struct loader_004548A0_t
	{
		bool m_points; // 0x0 "Points" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4548a0
	};

	struct loader_00454920_t
	{
		int32_t m_name; // 0x0 "Name" loader=0x454920
		// alias +0x0 "Round" lane=0x0 byte=0 mask=0xff shift=0 loader=0x454920
	};

	struct loader_0045F710_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x45f710
		// alias +0x0 "PosterModel" (int32_t)
	};

	struct loader_0046A500_t
	{
		bool m_bestlaptime; // 0x0 "BestLapTime" lane=0x0 byte=0 mask=0xff shift=0 loader=0x46a500
		// alias +0x0 "Boat" (int32_t)
		// alias +0x0 "CircuitRace" (int32_t)
		// alias +0x0 "DriverName" (int32_t)
		// alias +0x0 "GameResults" (int32_t)
		// alias +0x0 "IsFinished" (int32_t)
		// alias +0x0 "LapsCompleted" lane=0x0 byte=0 mask=0xff shift=0 loader=0x46a500
		// alias +0x0 "Table" (int32_t)
		// alias +0x0 "TierEntry" (int32_t)
		// alias +0x0 "TierName" (int32_t)
		// alias +0x0 "TotalTime" lane=0x0 byte=0 mask=0xff shift=0 loader=0x46a500
		std::uint8_t pad_0x1[0x23];
		float m_bestlaptime_1; // 0x24 "BestLapTime" loader=0x46a500
		// alias +0x24 "TierTime" (float)
	};

	struct loader_0046B710_t
	{
		bool m_lapscompleted; // 0x0 "LapsCompleted" lane=0x0 byte=0 mask=0xff shift=0 loader=0x46b710
	};

	struct loader_0046B95A_t
	{
		int32_t m_islocal; // 0x0 "IsLocal" loader=0x46b95a
	};

	struct loader_0046B979_t
	{
		int32_t m_ishuman; // 0x0 "IsHuman" loader=0x46b979
	};

	struct loader_0046B998_t
	{
		int32_t m_drivername; // 0x0 "DriverName" loader=0x46b998
	};

	struct loader_0046B9EE_t
	{
		bool m_padindex; // 0x0 "PadIndex" lane=0x0 byte=0 mask=0xff shift=0 loader=0x46b9ee
	};

	struct loader_00477240_t
	{
		int32_t m_ghosttable; // 0x0 "GhostTable" loader=0x477240
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "TotalTime" lane=0x0 byte=0 mask=0xff shift=0 loader=0x477240
	};

	struct loader_004795EE_t
	{
		int32_t m_vudbasset; // 0x0 "VuDBAsset" loader=0x4795ee
	};

	struct loader_004795FA_t
	{
		int32_t m_track; // 0x0 "Track" loader=0x4795fa
	};

	struct loader_00479621_t
	{
		std::uint8_t pad_0x0[0x94];
		int32_t m_choices; // 0x94 "Choices" loader=0x479621
	};

	struct loader_00479678_t
	{
		std::uint8_t pad_0x0[0xb4];
		int32_t m_value; // 0xb4 "Value" loader=0x479678
	};

	struct loader_004796FD_t
	{
		std::uint8_t pad_0x0[0xb4];
		int32_t m_stringid; // 0xb4 "StringID" loader=0x4796fd
	};

	struct loader_0047E2B0_t
	{
		int32_t m_course; // 0x0 "Course" loader=0x47e2b0
		// alias +0x0 "GameConfig" (int32_t)
		// alias +0x0 "Mode" (int32_t)
		// alias +0x0 "Track" (int32_t)
	};

	struct loader_0047FE90_t
	{
		int32_t m_image; // 0x0 "Image" loader=0x47fe90
		// alias +0x0 "Mode" (int32_t)
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "StringID" (int32_t)
		// alias +0x0 "Type" (int32_t)
	};

	struct loader_00481CE0_t
	{
		int32_t m_boats; // 0x0 "Boats" loader=0x481ce0
		// alias +0x0 "Difficulty" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
		std::uint8_t pad_0x4[0xc];
		int32_t m_ischampionship; // 0x10 "IsChampionship" loader=0x481ce0
		std::uint8_t pad_0x14[0x38];
		bool m_lapcount; // 0x4c "LapCount" lane=0x48 byte=4 mask=0xff00000000 shift=32 loader=0x481ce0
	};

	struct loader_00484280_t
	{
		int32_t m_gameresults; // 0x0 "GameResults" loader=0x484280
	};

	struct loader_0048DA90_t
	{
		bool m_totaltime; // 0x0 "TotalTime" lane=0x0 byte=0 mask=0xff shift=0 loader=0x48da90
		std::uint8_t pad_0x1[0x23];
		float m_totaltime_1; // 0x24 "TotalTime" loader=0x48da90
	};

	struct loader_00490490_t
	{
		bool m_totaltime; // 0x0 "TotalTime" lane=0x0 byte=0 mask=0xff shift=0 loader=0x490490
		std::uint8_t pad_0x1[0x23];
		float m_totaltime_1; // 0x24 "TotalTime" loader=0x490490
	};

	struct loader_00492480_t
	{
		int32_t m_finished; // 0x0 "Finished" loader=0x492480
		std::uint8_t pad_0x4[0x20];
		float m_totaltime; // 0x24 "TotalTime" loader=0x492480
	};

	struct loader_00492680_t
	{
		int32_t m_screen; // 0x0 "Screen" loader=0x492680
	};

	struct loader_004AA4C0_t
	{
		int32_t m_achievements; // 0x0 "Achievements" loader=0x4aa4c0
		// alias +0x0 "LocalUnlocked" (int32_t)
		// alias +0x0 "ServerUnlocked" (int32_t)
	};

	struct loader_004B07C0_t
	{
		int32_t m_leaderboards; // 0x0 "Leaderboards" loader=0x4b07c0
		// alias +0x0 "LocalValue" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b07c0
		// alias +0x0 "ServerValue" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b07c0
		// alias +0x0 "VuDBAsset" (int32_t)
	};

	struct loader_004B4100_t
	{
		VuVector2 m_progress; // 0x0 "Progress" loader=0x4b4100
	};

	struct loader_004B6A90_t
	{
		std::uint8_t pad_0x0[0xfc];
		int32_t m_unlock; // 0xfc "Unlock" loader=0x4b6a90
	};

	struct loader_004B6BA0_t
	{
		bool m_localmultiplayercredits; // 0x0 "LocalMultiplayerCredits" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b6ba0
		// alias +0x0 "OnlineMultiplayerCredits" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b6ba0
		// alias +0x0 "TotalCredits" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b6ba0
		std::uint8_t pad_0x1[0x1f];
		bool m_feats; // 0x20 "Feats" lane=0x20 byte=0 mask=0xff shift=0 loader=0x4b6ba0
	};

	struct loader_004B73B0_t
	{
		bool m_credits; // 0x0 "Credits" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4b73b0
	};

	struct loader_004B75D0_t
	{
		std::uint8_t pad_0x0[0xe8];
		int32_t m_feats; // 0xe8 "Feats" loader=0x4b75d0
	};

	struct loader_004B9160_t
	{
		int32_t m_devrestart; // 0x0 "DevRestart" loader=0x4b9160
	};

	struct loader_004BA060_t
	{
		int32_t m_gamedata; // 0x0 "GameData" loader=0x4ba060
		// alias +0x0 "TutorialShown" (int32_t)
	};

	struct loader_004BAE80_t
	{
		int32_t m_pausemenubackgroundcolor; // 0x0 "PauseMenuBackgroundColor" loader=0x4bae80
		// alias +0x0 "UI" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
		std::uint8_t pad_0x4[0xec];
		float m_transitionduration; // 0xf0 "TransitionDuration" loader=0x4bae80
		// alias +0xf0 "UI" (float)
		// alias +0xf0 "VuDBAsset" (float)
	};

	struct loader_004BCFF0_t
	{
		int32_t m_filter; // 0x0 "Filter" loader=0x4bcff0
		std::uint8_t pad_0x4[0xffffff74];
		int32_t m_assets; // 0xffffff78 "Assets" loader=0x4bcff0
		int32_t m_filter_1; // 0xffffff7c "Filter" loader=0x4bcff0
	};

	struct loader_004C88C0_t
	{
		int32_t m_skeleton; // 0x0 "Skeleton" loader=0x4c88c0
	};

	struct loader_004D2440_t
	{
		int32_t m_assetnames; // 0x0 "AssetNames" loader=0x4d2440
	};

	struct loader_004D24F0_t
	{
		int32_t m_assetnames; // 0x0 "AssetNames" loader=0x4d24f0
		// alias +0x0 "AssetType" (int32_t)
	};

	struct loader_004D2DE0_t
	{
		int32_t m_actiongamedata; // 0x0 "ActionGameData" loader=0x4d2de0
		// alias +0x0 "AudioEvent" (int32_t)
		// alias +0x0 "Championship" (int32_t)
		// alias +0x0 "Course" (int32_t)
		// alias +0x0 "GameData" (int32_t)
		// alias +0x0 "GameType" (int32_t)
		// alias +0x0 "Level" (int32_t)
		// alias +0x0 "MusicList" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
		std::uint8_t pad_0x4[0x20];
		float m_volume; // 0x24 "Volume" loader=0x4d2de0
	};

	struct loader_004D3690_t
	{
		int32_t m_actiongamedata; // 0x0 "ActionGameData" loader=0x4d3690
		// alias +0x0 "GameData" (int32_t)
		// alias +0x0 "IsChampionship" (int32_t)
		// alias +0x0 "Screens/Loading" (int32_t)
	};

	struct loader_004D37B0_t
	{
		int32_t m_boat; // 0x0 "Boat" loader=0x4d37b0
		// alias +0x0 "Class" (int32_t)
		// alias +0x0 "GameData" (int32_t)
		// alias +0x0 "VuDBAsset" (int32_t)
		std::uint8_t pad_0x4[0xf4];
		int32_t m_driver_type; // 0xf8 "Driver Type" loader=0x4d37b0
		// alias +0xf8 "Properties" (int32_t)
		int32_t m_actiongamedata; // 0xfc "ActionGameData" loader=0x4d37b0
		// alias +0xfc "Boats" (int32_t)
	};

	struct loader_004EFBB0_t
	{
		int32_t m_assets; // 0x0 "Assets" loader=0x4efbb0
		std::uint8_t pad_0x4[0x2c];
		std::uint64_t m_pack_0x30; // 8-byte packed lane @ 0x30 pack_mask=0x1095216660735
		// m_contentcategory +0x30 "ContentCategory" lane=0x30 byte=0 mask=0xff shift=0 loader=0x4efbb0
		// m_version +0x34 "Version" lane=0x30 byte=4 mask=0xff00000000 shift=32 loader=0x4efbb0
		bool m_licensemask; // 0x38 "LicenseMask" lane=0x38 byte=0 mask=0xff shift=0 loader=0x4efbb0
	};

	struct loader_004F0EF0_t
	{
		int32_t m_file; // 0x0 "File" loader=0x4f0ef0
	};

	struct loader_004F1330_t
	{
		std::uint8_t pad_0x0[0xa4];
		int32_t m_file; // 0xa4 "File" loader=0x4f1330
	};

	struct loader_004F1CF0_t
	{
		int32_t m_skus; // 0x0 "Skus" loader=0x4f1cf0
		std::uint8_t pad_0x4[0xa0];
		int32_t m_skus_1; // 0xa4 "Skus" loader=0x4f1cf0
	};

	struct loader_004F1DC0_t
	{
		// unresolved +0x0 "Filter" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4f1dc0
	};

	struct loader_004FE0F0_t
	{
		int32_t m_base64; // 0x0 "Base64" loader=0x4fe0f0
	};

	struct loader_004FE740_t
	{
		bool m_hour; // 0x0 "Hour" lane=0x0 byte=0 mask=0xff shift=0 loader=0x4fe740
		// alias +0x0 "Minute" (int32_t)
		std::uint8_t pad_0x1[0x5];
		int32_t m_second; // 0x6 "Second" loader=0x4fe740
		std::uint8_t pad_0xa[0xea];
		bool m_day; // 0xf4 "Day" lane=0xf0 byte=4 mask=0xff00000000 shift=32 loader=0x4fe740
		std::uint8_t pad_0xf5[0x3];
		bool m_month; // 0xf8 "Month" lane=0xf8 byte=0 mask=0xff shift=0 loader=0x4fe740
		std::uint8_t pad_0xf9[0x3];
		int32_t m_year; // 0xfc "Year" loader=0x4fe740
	};

	struct loader_00501300_t
	{
		int32_t m_name; // 0x0 "name" loader=0x501300
		// alias +0x0 "type" (int32_t)
		std::uint8_t pad_0x4[0xac];
		int32_t m_data; // 0xb0 "data" loader=0x501300
	};

	struct loader_005015D0_t
	{
		int32_t m_childentities; // 0x0 "ChildEntities" loader=0x5015d0
		// alias +0x0 "Components" (int32_t)
		// alias +0x0 "Properties" (int32_t)
	};

	struct loader_00501F70_t
	{
		int32_t m_properties; // 0x0 "Properties" loader=0x501f70
	};

	struct loader_00502010_t
	{
		std::uint8_t pad_0x0[0xf0];
		int32_t m_properties; // 0xf0 "Properties" loader=0x502010
	};

	struct loader_00502430_t
	{
		int32_t m_entityname; // 0x0 "EntityName" loader=0x502430
		// alias +0x0 "PlugName" (int32_t)
	};

	struct loader_005049E0_t
	{
		int32_t m_entityname; // 0x0 "EntityName" loader=0x5049e0
		// alias +0x0 "RefName" (int32_t)
	};

	struct loader_005116E0_t
	{
		std::uint8_t pad_0x0[0xf4];
		int32_t m_axes; // 0xf4 "Axes" loader=0x5116e0
		// alias +0xf4 "Buttons" (int32_t)
	};

	struct loader_00511C90_t
	{
		VuVector3 m_index; // 0x0 "Index" loader=0x511c90
		// alias +0x0 "Type" (int32_t)
	};

	struct loader_0051B950_t
	{
		int32_t m_value; // 0x0 "Value" loader=0x51b950
		std::uint8_t pad_0x4[0xf0];
		int32_t m_name; // 0xf4 "Name" loader=0x51b950
		std::uint8_t pad_0xf8[0x4];
		int32_t m_parameters; // 0xfc "Parameters" loader=0x51b950
	};

	struct loader_00521F20_t
	{
		std::uint8_t pad_0x0[0xfffff8fc];
		int32_t m_constants; // 0xfffff8fc "Constants" loader=0x521f20
		// alias +0xfffff8fc "Textures" (int32_t)
	};

	struct loader_00522AE0_t
	{
		int32_t m_file; // 0x0 "File" loader=0x522ae0
	};

	struct loader_0052EF50_t
	{
		bool m_parentindex; // 0x0 "ParentIndex" lane=0x0 byte=0 mask=0xff shift=0 loader=0x52ef50
		std::uint8_t pad_0x1[0xeb];
		int32_t m_transform; // 0xec "Transform" loader=0x52ef50
	};

	struct loader_0053D210_t
	{
		int32_t m_charcodes; // 0x0 "CharCodes" loader=0x53d210
		// alias +0x0 "Options" (int32_t)
		// alias +0x0 "Strings" (int32_t)
		// alias +0x0 "WW_NOHANGULWRAP" (int32_t)
		// alias +0x0 "WW_PROHIBITION" (int32_t)
	};

	struct loader_00542A80_t
	{
		int32_t m_file; // 0x0 "File" loader=0x542a80
		// alias +0x0 "FlipX" (int32_t)
	};

	struct loader_005552D0_t
	{
		int32_t m_childentities; // 0x0 "ChildEntities" loader=0x5552d0
		// alias +0x0 "type" (int32_t)
		std::uint8_t pad_0x4[0xec];
		int32_t m_data; // 0xf0 "data" loader=0x5552d0
	};

	struct loader_0055FAD0_t
	{
		int32_t m_file; // 0x0 "File" loader=0x55fad0
	};

	struct loader_0055FC50_t
	{
		int32_t m_langs; // 0x0 "Langs" loader=0x55fc50
	};

	struct loader_0055FCE0_t
	{
		std::uint8_t pad_0x0[0xa8];
		int32_t m_langs; // 0xa8 "Langs" loader=0x55fce0
	};

	struct loader_00560E10_t
	{
		std::uint8_t pad_0x0[0xfc];
		int32_t m_nodes; // 0xfc "Nodes" loader=0x560e10
	};

	struct loader_00561AB0_t
	{
		int32_t m_frames; // 0x0 "Frames" loader=0x561ab0
		// alias +0x0 "Skeleton" (int32_t)
		std::uint8_t pad_0x4[0xc];
		bool m_framecount; // 0x10 "FrameCount" lane=0x10 byte=0 mask=0xff shift=0 loader=0x561ab0
	};

	struct loader_00563EE0_t
	{
		int32_t m_basetype; // 0x0 "BaseType" loader=0x563ee0
		std::uint8_t pad_0x4[0xe8];
		int32_t m_type; // 0xec "Type" loader=0x563ee0
	};

	struct loader_00580E10_t
	{
		std::uint8_t pad_0x0[0x38];
		int32_t m_shaders; // 0x38 "Shaders" loader=0x580e10
	};

	struct loader_00580F00_t
	{
		std::uint8_t pad_0x0[0xe0];
		int32_t m_name; // 0xe0 "Name" loader=0x580f00
		// alias +0xe0 "ShaderAssetName" (int32_t)
		std::uint8_t pad_0xe4[0x4];
		int32_t m_meshes; // 0xe8 "Meshes" loader=0x580f00
		std::uint8_t pad_0xec[0x8];
		int32_t m_name_1; // 0xf4 "Name" loader=0x580f00
		std::uint8_t pad_0xf8[0x4];
		int32_t m_nodes; // 0xfc "Nodes" loader=0x580f00
	};

	struct loader_00581530_t
	{
		int32_t m_data; // 0x0 "Data" loader=0x581530
		// alias +0x0 "Indices" (int32_t)
		// alias +0x0 "NumVerts" lane=0x0 byte=0 mask=0xff shift=0 loader=0x581530
		// alias +0x0 "Parts" (int32_t)
		// alias +0x0 "Verts" (int32_t)
		std::uint8_t pad_0x4[0x20];
		bool m_indexcount; // 0x24 "IndexCount" lane=0x20 byte=4 mask=0xff00000000 shift=32 loader=0x581530
		// alias +0x24 "Indices" lane=0x20 byte=4 mask=0xff00000000 shift=32 loader=0x581530
		std::uint8_t pad_0x25[0x9b];
		int32_t m_vertexdeclaration; // 0xc0 "VertexDeclaration" loader=0x581530
		std::uint8_t pad_0xc4[0x14];
		bool m_vertexsize; // 0xd8 "VertexSize" lane=0xd8 byte=0 mask=0xff shift=0 loader=0x581530
	};

	struct loader_005818A0_t
	{
		int32_t m_nodes; // 0x0 "Nodes" loader=0x5818a0
		// alias +0x0 "Transform" (int32_t)
		std::uint8_t pad_0x4[0xa8];
		int32_t m_mesh; // 0xac "Mesh" loader=0x5818a0
		// alias +0xac "MeshInstance" (int32_t)
	};

	struct loader_00581A50_t
	{
		std::uint8_t pad_0x0[0x8];
		bool m_tricount; // 0x8 "TriCount" lane=0x8 byte=0 mask=0xff shift=0 loader=0x581a50
		std::uint8_t pad_0x9[0xdb];
		int32_t m_shader; // 0xe4 "Shader" loader=0x581a50
		std::uint8_t pad_0xe8[0xc];
		int32_t m_name; // 0xf4 "Name" loader=0x581a50
		bool m_startindex; // 0xf8 "StartIndex" lane=0xf8 byte=0 mask=0xff shift=0 loader=0x581a50
	};

	struct loader_00592D60_t
	{
		int32_t m_name; // 0x0 "Name" loader=0x592d60
		// alias +0x0 "ShaderAssetName" (int32_t)
	};

	struct loader_00593070_t
	{
		int32_t m_choices; // 0x0 "Choices" loader=0x593070
		// alias +0x0 "Default" (int32_t)
		// alias +0x0 "Enabled" lane=0x0 byte=0 mask=0xff shift=0 loader=0x593070
		// alias +0x0 "UvSetChoices" (int32_t)
		// alias +0x0 "UvSetDefault" (int32_t)
		// alias +0x0 "UvSetMacro" (int32_t)
		// alias +0x0 "UvSetValue" (int32_t)
		// alias +0x0 "Value" lane=0x0 byte=0 mask=0xff shift=0 loader=0x593070
		std::uint8_t pad_0x4[0x80];
		int32_t m_type; // 0x84 "Type" loader=0x593070
		vu_custom_t m_name; // 0x88 "Name" loader=0x593070
		std::uint8_t pad_0x8c[0xfffffee8];
		int32_t m_parameters; // 0xffffff74 "Parameters" loader=0x593070
	};

	struct loader_00593780_t
	{
		int32_t m_name; // 0x0 "Name" loader=0x593780
		// alias +0x0 "Type" (int32_t)
	};

	struct loader_005A8200_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5a8200
	};

	struct loader_005ADFE0_t
	{
		int32_t m_addressv; // 0x0 "AddressV" loader=0x5adfe0
		// alias +0x0 "Compression" (int32_t)
		// alias +0x0 "ETC Dithering" (int32_t)
		// alias +0x0 "ETC Quality" (int32_t)
		// alias +0x0 "File" (int32_t)
		// alias +0x0 "MagFilter" (int32_t)
		// alias +0x0 "Type" (int32_t)
		std::uint8_t pad_0x4[0x54];
		int32_t m_minfilter; // 0x58 "MinFilter" loader=0x5adfe0
		std::uint8_t pad_0x5c[0x88];
		int32_t m_mipfilter; // 0xe4 "MipFilter" loader=0x5adfe0
	};

	struct loader_005C1060_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5c1060
	};

	struct loader_005C1830_t
	{
		std::uint8_t pad_0x0[0xd0];
		int32_t m_meshes; // 0xd0 "Meshes" loader=0x5c1830
		std::uint8_t pad_0xd4[0x24];
		int32_t m_shaders; // 0xf8 "Shaders" loader=0x5c1830
	};

	struct loader_005C2200_t
	{
		int32_t m_meshinstance; // 0x0 "MeshInstance" loader=0x5c2200
		// alias +0x0 "Name" (int32_t)
		std::uint8_t pad_0x4[0xb0];
		float m_transform; // 0xb4 "Transform" loader=0x5c2200
		std::uint8_t pad_0xb8[0x28];
		int32_t m_nodes; // 0xe0 "Nodes" loader=0x5c2200
	};

	struct loader_005C5B20_t
	{
		int32_t m_id; // 0x0 "ID" loader=0x5c5b20
	};

	struct loader_005C7A90_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5c7a90
	};

	struct loader_005C7ED0_t
	{
		int32_t m_clipchannel; // 0x0 "ClipChannel" loader=0x5c7ed0
		// alias +0x0 "DecalChannel" (int32_t)
		// alias +0x0 "File" (int32_t)
		// alias +0x0 "FoamChannel" (int32_t)
		// alias +0x0 "ShadowChannel" (int32_t)
	};

	struct loader_005C8D90_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5c8d90
	};

	struct loader_005CAD00_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5cad00
	};

	struct loader_005CB070_t
	{
		int32_t m_file; // 0x0 "File" loader=0x5cb070
	};

	struct loader_005CB4C0_t
	{
		int32_t m_decompress; // 0x0 "Decompress" loader=0x5cb4c0
		// alias +0x0 "File" (int32_t)
		// alias +0x0 "InstanceCount" lane=0x0 byte=0 mask=0xff shift=0 loader=0x5cb4c0
	};

	struct loader_005E3DF0_t
	{
		int32_t m_persistentdata; // 0x0 "PersistentData" loader=0x5e3df0
	};

	struct loader_00615F40_t
	{
		int32_t m_data; // 0x0 "Data" loader=0x615f40
		// alias +0x0 "IndexCount" lane=0x0 byte=0 mask=0xff shift=0 loader=0x615f40
		// alias +0x0 "Indices" (int32_t)
		// alias +0x0 "Max" (int32_t)
		// alias +0x0 "Name" (int32_t)
		// alias +0x0 "Parts" (int32_t)
		// alias +0x0 "Shader" (int32_t)
		// alias +0x0 "StartIndex" lane=0x0 byte=0 mask=0xff shift=0 loader=0x615f40
		// alias +0x0 "TriCount" lane=0x0 byte=0 mask=0xff shift=0 loader=0x615f40
		// alias +0x0 "VertexDeclaration" (int32_t)
		// alias +0x0 "Verts" (int32_t)
	};

	struct loader_00617788_t
	{
		int32_t m_shader; // 0x0 "Shader" loader=0x617788
	};

	struct loader_00617879_t
	{
		int32_t m_aabb; // 0x0 "Aabb" loader=0x617879
	};

	struct loader_00617887_t
	{
		int32_t m_min; // 0x0 "Min" loader=0x617887
	};

	struct loader_006178A5_t
	{
		int32_t m_max; // 0x0 "Max" loader=0x6178a5
	};

	struct loader_00618310_t
	{
		int32_t m_mesh; // 0x0 "Mesh" loader=0x618310
	};

	struct loader_006184B0_t
	{
		int32_t m_file; // 0x0 "File" loader=0x6184b0
	};

	struct loader_00618B60_t
	{
		std::uint8_t pad_0x0[0x4];
		int32_t m_data; // 0x4 "Data" loader=0x618b60
		std::uint8_t pad_0x8[0x9c];
		int32_t m_images; // 0xa4 "Images" loader=0x618b60
		// alias +0xa4 "Texture" lane=0xa0 byte=4 mask=0xff00000000 shift=32 loader=0x618b60
		std::uint8_t pad_0xa8[0x4];
		float m_ascender; // 0xac "Ascender" loader=0x618b60
		// alias +0xac "Descender" (float)
		// alias +0xac "MaxRadius" (float)
		// alias +0xac "Metrics" (float)
		std::uint8_t pad_0xb0[0x2c];
		bool m_height; // 0xdc "Height" lane=0xd8 byte=4 mask=0xff00000000 shift=32 loader=0x618b60
		std::uint8_t pad_0xdd[0x3];
		bool m_width; // 0xe0 "Width" lane=0xe0 byte=0 mask=0xff shift=0 loader=0x618b60
		std::uint8_t pad_0xe1[0xb];
		int32_t m_characters; // 0xec "Characters" loader=0x618b60
		// alias +0xec "TextureAsset" (int32_t)
	};

	struct loader_00619870_t
	{
		bool m_code; // 0x0 "Code" lane=0x0 byte=0 mask=0xff shift=0 loader=0x619870
		// alias +0x0 "ImageIndex" lane=0x0 byte=0 mask=0xff shift=0 loader=0x619870
		std::uint8_t pad_0x1[0x7];
		float m_advance; // 0x8 "Advance" loader=0x619870
		// alias +0x8 "DstB" (float)
		// alias +0x8 "DstL" (float)
		// alias +0x8 "DstR" (float)
		// alias +0x8 "DstT" (float)
		// alias +0x8 "SrcB" (float)
		// alias +0x8 "SrcL" (float)
		// alias +0x8 "SrcR" (float)
		// alias +0x8 "SrcT" (float)
		std::uint8_t pad_0xc[0xf0];
		int32_t m_isimage; // 0xfc "IsImage" loader=0x619870
	};

	struct loader_0062FA90_t
	{
		int32_t m_elements; // 0x0 "Elements" loader=0x62fa90
		// alias +0x0 "Type" (int32_t)
	};

	struct loader_00630100_t
	{
		VuColor m_align; // 0x0 "Align" loader=0x630100
		// alias +0x0 "Font" (int32_t)
		// alias +0x0 "StringID" (int32_t)
	};

	struct loader_00630610_t
	{
		int32_t m_align; // 0x0 "Align" loader=0x630610
		int32_t m_texture; // 0x4 "Texture" loader=0x630610
	};

	struct loader_00630B40_t
	{
		std::uint8_t pad_0x0[0x8];
		float m_amount; // 0x8 "Amount" loader=0x630b40
	};

}
