#pragma once
// auto-generated by vu static sdk dumper

#include <cstdint>

namespace Vu::SDK
{
	using vu_string_t = char*;
	using vu_asset_ref_t = void*;
	using vu_custom_t = std::uint8_t;

	// Engine math types (from VuBasicProperty<VuVectorN> / live size).
	struct VuVector2
	{
		float x{}, y{};
	};
	static_assert(sizeof(VuVector2) == 8);

	struct VuVector3
	{
		float x{}, y{}, z{};
		float pad{}; // storage is 16 bytes (property copies two QWORDs)
	};
	static_assert(sizeof(VuVector3) == 16);

	struct VuColor
	{
		std::uint8_t r{}, g{}, b{}, a{};
	};
	static_assert(sizeof(VuColor) == 4);

	struct VuRect
	{
		float left{}, top{}, right{}, bottom{};
	};
	static_assert(sizeof(VuRect) == 16);

	struct VuMatrix4
	{
		float m[16];
	};

	using vu_vector_t = VuVector3; // backward-compatible alias
	using vu_matrix4_t = VuMatrix4;

	// 8-byte packed lane helpers (byte members share an aligned uint64_t).
	[[nodiscard]] constexpr std::uint64_t vu_byte_mask(std::uint32_t byte_index) noexcept
	{
		return 0xFFull << (byte_index * 8u);
	}
	[[nodiscard]] constexpr std::uint8_t vu_pack_get(std::uint64_t pack, std::uint32_t byte_index) noexcept
	{
		return static_cast<std::uint8_t>((pack >> (byte_index * 8u)) & 0xFFu);
	}
	constexpr void vu_pack_set(std::uint64_t& pack, std::uint32_t byte_index, std::uint8_t value) noexcept
	{
		const auto shift = byte_index * 8u;
		pack = (pack & ~(0xFFull << shift)) | (static_cast<std::uint64_t>(value) << shift);
	}
}
